const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/Users/ludko/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.PREVIEW_URL||'http://127.0.0.1:5180/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__F1__?.loaded||window.__F1__?.error);await page.screenshot({path:'reports/web-desktop.png'});const samples=[];
for(const i of [0,1,2,3,4,5]){await page.evaluate(i=>{const el=document.querySelector('.chapters');scrollTo({top:(el.offsetHeight-innerHeight)*i/5,behavior:'instant'})},i);await page.waitForTimeout(850);samples.push(await page.evaluate(()=>({...window.__F1__})));if(i===3)await page.screenshot({path:'reports/web-mguh.png'})}
await page.evaluate(()=>{const el=document.querySelector('.chapters');scrollTo({top:(el.offsetHeight-innerHeight)*2/5,behavior:'instant'})});await page.waitForTimeout(900);await page.screenshot({path:'reports/web-engine-assembled.png'});
await page.locator('[data-engine-mode="cutaway"]').click();await page.locator('#engine-run').click();const startAngle=await page.evaluate(()=>window.__F1__.crankAngle);await page.waitForTimeout(500);const mechanism=await page.evaluate(()=>({...window.__F1__}));await page.locator('#engine-run').click();await page.screenshot({path:'reports/web-engine-cutaway.png'});await page.locator('[data-engine-mode="assembled"]').click();
await page.locator('#rotate').click();const orbit=await page.locator('#rotate').getAttribute('aria-pressed');await page.locator('#reset').click();const reset=await page.locator('#rotate').getAttribute('aria-pressed');
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(1000);await page.screenshot({path:'reports/web-mobile.png'});await page.evaluate(()=>{const el=document.querySelector('.chapters');scrollTo({top:(el.offsetHeight-innerHeight)*2/5,behavior:'instant'})});await page.waitForTimeout(900);await page.locator('[data-engine-mode="cutaway"]').click();await page.screenshot({path:'reports/web-mobile-engine.png'});const mobile=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));
const fall=await browser.newPage();await fall.addInitScript(()=>{const g=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return t.includes('webgl')?null:g.call(this,t,...a)}});await fall.goto(process.env.PREVIEW_URL||'http://127.0.0.1:5180/',{waitUntil:'networkidle'});const fallback=await fall.locator('#fallback').isVisible();
const assets=[];for(const path of ['assets/models/f1-power-unit.glb','assets/video/f1-power-unit-master.mp4','assets/video/captions.vtt','data/ground_truth_physics.json','docs/technical-notes.md']){const r=await page.request.get(new URL(path,process.env.PREVIEW_URL||'http://127.0.0.1:5180/').href);assets.push({path,status:r.status()})}await page.locator('video').evaluate(v=>v.load());await page.waitForFunction(()=>document.querySelector('video').readyState>=1);const video=await page.locator('video').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,captions:v.textTracks.length}));const report={assets,video,mechanism,status:mechanism.pistonCount===6&&mechanism.rodLengthError<1e-10&&mechanism.crankAngle>startAngle&&assets.every(a=>a.status===200)&&video.duration===120&&errors.length===0&&samples.every((s,i)=>s.loaded&&s.chapter===i)&&mobile.width===mobile.scrollWidth&&orbit==='true'&&reset==='false'&&fallback?'passed':'failed',samples,mobile,orbit,reset,fallback,errors};fs.writeFileSync('reports/web-validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
