const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/Users/ludko/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.PREVIEW_URL||'http://127.0.0.1:5181/?engine=ra166e',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__F1__?.loaded||window.__F1__?.error);await page.screenshot({path:'reports/ra166e-scroll-desktop.png'});const samples=[];
for(const i of [0,1,2,3,4,5]){await page.evaluate(i=>{const el=document.querySelector('.chapters');scrollTo({top:(el.offsetHeight-innerHeight)*i/5,behavior:'instant'})},i);await page.waitForTimeout(850);samples.push(await page.evaluate(()=>({...window.__F1__})));if(i===3)await page.screenshot({path:'reports/ra166e-scroll-mguh.png'})}
await page.evaluate(()=>{const el=document.querySelector('.chapters');scrollTo({top:(el.offsetHeight-innerHeight)*2/5,behavior:'instant'})});await page.waitForTimeout(900);await page.screenshot({path:'reports/ra166e-scroll-engine-assembled.png'});
await page.locator('[data-engine-mode="cutaway"]').click();await page.locator('#engine-run').click();const startAngle=await page.evaluate(()=>window.__F1__.crankAngle);const joints=await page.evaluate(async()=>{let maxError=0;const start=window.__F1__.crankAngle;for(let i=0;i<180;i++){await new Promise(requestAnimationFrame);maxError=Math.max(maxError,window.__F1__.jointError);}return {maxError,sweep:window.__F1__.crankAngle-start};});const mechanism=await page.evaluate(()=>({...window.__F1__}));await page.locator('#engine-run').click();await page.screenshot({path:'reports/ra166e-scroll-engine-cutaway.png'});await page.locator('[data-engine-mode="assembled"]').click();
await page.locator('#rotate').click();const orbit=await page.locator('#rotate').getAttribute('aria-pressed');await page.locator('#reset').click();const reset=await page.locator('#rotate').getAttribute('aria-pressed');
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(1000);await page.screenshot({path:'reports/ra166e-scroll-mobile.png'});await page.evaluate(()=>{const el=document.querySelector('.chapters');scrollTo({top:(el.offsetHeight-innerHeight)*2/5,behavior:'instant'})});await page.waitForTimeout(900);await page.locator('[data-engine-mode="cutaway"]').click();await page.screenshot({path:'reports/ra166e-scroll-mobile-engine.png'});const mobile=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));
const fall=await browser.newPage();await fall.addInitScript(()=>{const g=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return t.includes('webgl')?null:g.call(this,t,...a)}});await fall.goto(process.env.PREVIEW_URL||'http://127.0.0.1:5181/?engine=ra166e',{waitUntil:'networkidle'});const fallback=await fall.locator('#fallback').isVisible();
const assets=[];for(const path of ['assets/models/f1-power-unit.glb','assets/video/f1-power-unit-master.mp4','assets/video/captions.vtt','data/ground_truth_physics.json','docs/technical-notes.md']){const r=await page.request.get(new URL(path,process.env.PREVIEW_URL||'http://127.0.0.1:5181/?engine=ra166e').href);assets.push({path,status:r.status()})}const report={assets,mechanism,joints,status:joints.maxError<1e-6&&joints.sweep>Math.PI*2&&mechanism.pistonCount===6&&mechanism.rodLengthError<1e-10&&mechanism.crankAngle>startAngle&&assets.every(a=>a.status===200)&&errors.length===0&&samples.every((s,i)=>s.loaded&&s.chapter===i)&&mobile.width===mobile.scrollWidth&&orbit==='true'&&reset==='false'&&fallback?'passed':'failed',samples,mobile,orbit,reset,fallback,errors};fs.writeFileSync('reports/ra166e-scroll-validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
